[package]
name = "hui-winit"
version = "0.1.0-alpha.3"
edition = "2021"

[dependencies]
hui = { version = "=0.1.0-alpha.3", path = "../hui", default-features = false }
winit = { version = "0.29", default-features = false }
glam = "0.25"
log = "0.4"
