[package]
name = "hui"
description = "Simple UI library for games and other interactive applications"
repository = "https://github.com/griffi-gh/hui"
readme = "../README.md"
authors = ["griffi-gh <prasol258@gmail.com>"]
rust-version = "1.75"
version = "0.1.0-alpha.3"
edition = "2021"
license = "GPL-3.0-or-later"
publish = true
include = [
  "assets/**/*",
  "src/**/*.rs",
  "Cargo.toml",
]

[dependencies]
hashbrown = "0.14"
nohash-hasher = "0.2"
glam = "0.25"
fontdue = "0.8"
rect_packer = "0.2"
log = "0.4"
nz = "0.3"
document-features = "0.2"

[features]
default = ["builtin_elements", "builtin_font", "pixel_perfect"]
## Enable the built-in font (ProggyTiny, adds 35kb to the executable)
builtin_font = []
## Enable the built-in elements (`Container`, `ProgressBar`, etc.)\
builtin_elements = ["builtin_container"]
## Enable only the `Container` component (which is essential for laying out other components)
builtin_container = []
## Round vertex positions to nearest integer coordinates (fixes blurry text)
pixel_perfect = []

#parallel = ["dep:rayon", "fontdue/parallel"]
